"""
Unit and Integration Test Suite for Milestone 11 — LLM Provider Abstraction & Cascading Router
Validates Pydantic schemas, individual providers, cascading fallback, simulation flags, and DB auditing.
"""

import pytest
from typing import Dict, Any, Tuple
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker, Session
from sqlalchemy.pool import StaticPool

import backend.models  # noqa: F401 - Register models
from backend.database.session import Base
from backend.config import settings
from backend.models.llm_invocation import LLMInvocation
from backend.models.enums import FailureCategory, StrategyType
from backend.integrations.llm.schemas import RecoveryDiagnosis
from backend.integrations.llm.base import LLMProvider, LLMProviderError
from backend.integrations.llm.deterministic_provider import DeterministicFallbackProvider
from backend.integrations.llm.openai_provider import OpenAIProvider
from backend.integrations.llm.gemini_provider import GeminiProvider
from backend.integrations.llm.router import LLMRouter
from backend.integrations.llm.prompts import build_user_prompt

# Setup test DB engine
test_engine = create_engine(
    "sqlite:///:memory:",
    connect_args={"check_same_thread": False},
    poolclass=StaticPool,
)
Base.metadata.create_all(bind=test_engine)
TestingSessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=test_engine)

@pytest.fixture
def db_session():
    """Clean in-memory DB session."""
    session = TestingSessionLocal()
    try:
        yield session
    finally:
        session.close()

@pytest.fixture
def sample_context() -> Dict[str, Any]:
    """Sample case context dictionary for testing."""
    return {
        "case": {
            "id": "case_test_123",
            "status": "SEGMENTED",
            "attempt_count": 0,
            "is_terminal": False,
        },
        "transaction": {
            "id": "txn_test_123",
            "razorpay_payment_id": "pay_test_999",
            "amount_paise": 150000, # ₹1,500
            "amount_rupees": 1500.0,
            "currency": "INR",
            "status": "FAILED",
            "failure_category": "AUTHENTICATION_FAILURE",
            "error_code": "BAD_REQUEST_ERROR",
            "error_description": "OTP verification failed",
            "payment_method": "card",
            "created_at": "2026-09-05T00:00:00+00:00",
            "age_hours": 1.5,
        },
        "customer": {
            "id": "cust_test_123",
            "email": "user@example.com",
            "phone": "+919876543210",
            "customer_type": "NEW",
            "contacts_count_24h": 0,
            "total_transactions": 1,
            "successful_transactions": 0,
            "failed_transactions": 1,
        },
        "segment": {
            "id": "seg_test_123",
            "name": "authentication_failure_card_mid_new",
            "failure_category": "AUTHENTICATION_FAILURE",
            "payment_method": "card",
            "amount_range": "MID",
            "customer_type": "NEW",
        },
        "recovery_history": {
            "attempt_count": 0,
            "action_history": [],
            "active_payment_link_id": None,
        },
    }

# Mock Provider implementations for controlled testing
class AlwaysSuccessMockProvider(LLMProvider):
    def __init__(self, provider_name: str, strategy: str = "PAYMENT_LINK"):
        self._name = provider_name
        self._strategy = strategy

    @property
    def name(self) -> str:
        return self._name

    @property
    def model_name(self) -> str:
        return f"{self._name}-mock-v1"

    def diagnose(self, context: Dict[str, Any]) -> Tuple[RecoveryDiagnosis, Dict[str, Any]]:
        diag = RecoveryDiagnosis(
            failure_category="AUTHENTICATION_FAILURE",
            diagnosis=f"Diagnosis generated by {self._name}",
            recoverability_score=0.8,
            confidence=0.9,
            recommended_strategy=self._strategy,
            reasoning_summary=f"Reasoning by {self._name}",
        )
        metadata = {"latency_ms": 150, "prompt_tokens": 100, "completion_tokens": 50}
        return diag, metadata

class AlwaysFailingMockProvider(LLMProvider):
    def __init__(self, provider_name: str):
        self._name = provider_name

    @property
    def name(self) -> str:
        return self._name

    @property
    def model_name(self) -> str:
        return f"{self._name}-fail-v1"

    def diagnose(self, context: Dict[str, Any]) -> Tuple[RecoveryDiagnosis, Dict[str, Any]]:
        raise LLMProviderError(self._name, f"Mock failure in {self._name}")

# -----------------------------------------------------------------------------
# 1. Pydantic Schema Validation Tests
# -----------------------------------------------------------------------------

def test_schema_valid_construction():
    diag = RecoveryDiagnosis(
        failure_category="AUTHENTICATION_FAILURE",
        diagnosis="User entered invalid OTP",
        recoverability_score=0.75,
        confidence=0.85,
        recommended_strategy="PAYMENT_LINK",
        reasoning_summary="Payment link allows retry",
    )
    assert diag.failure_category == "AUTHENTICATION_FAILURE"
    assert diag.recommended_strategy == "PAYMENT_LINK"

def test_schema_lowercase_enum_normalization():
    diag = RecoveryDiagnosis(
        failure_category="authentication_failure",
        diagnosis="Normalized category",
        recoverability_score=0.5,
        confidence=0.5,
        recommended_strategy="payment_link",
        reasoning_summary="Normalized strategy",
    )
    assert diag.failure_category == "AUTHENTICATION_FAILURE"
    assert diag.recommended_strategy == "PAYMENT_LINK"

def test_schema_invalid_enum_rejected():
    with pytest.raises(ValueError):
        RecoveryDiagnosis(
            failure_category="INVALID_CATEGORY_NAME",
            diagnosis="Bad category",
            recoverability_score=0.5,
            confidence=0.5,
            recommended_strategy="PAYMENT_LINK",
            reasoning_summary="Reasoning",
        )

# -----------------------------------------------------------------------------
# 2. Deterministic Fallback Provider Tests
# -----------------------------------------------------------------------------

def test_deterministic_provider_auth_failure(sample_context):
    provider = DeterministicFallbackProvider()
    diag, meta = provider.diagnose(sample_context)

    assert provider.name == "deterministic"
    assert provider.model_name == "rule-engine-v1"
    assert diag.failure_category == "AUTHENTICATION_FAILURE"
    assert diag.recommended_strategy == "PAYMENT_LINK"
    assert meta["latency_ms"] >= 1

def test_deterministic_provider_high_value(sample_context):
    sample_context["transaction"]["amount_paise"] = 1500000 # ₹15,000
    provider = DeterministicFallbackProvider()
    diag, _ = provider.diagnose(sample_context)

    assert diag.recommended_strategy == "HUMAN_REVIEW"
    assert "high-value threshold" in diag.reasoning_summary.lower()

def test_deterministic_provider_max_retries_reached(sample_context):
    sample_context["recovery_history"]["attempt_count"] = 2
    provider = DeterministicFallbackProvider()
    diag, _ = provider.diagnose(sample_context)

    assert diag.recommended_strategy == "NO_ACTION"
    assert "safety limit" in diag.reasoning_summary.lower()

# -----------------------------------------------------------------------------
# 3. Router Cascading Fallback & DB Auditing Tests
# -----------------------------------------------------------------------------

def test_router_primary_success(db_session: Session, sample_context):
    """Verify primary provider succeeds and logs single invocation with fallback_triggered=False."""
    p1 = AlwaysSuccessMockProvider("openai")
    p2 = AlwaysSuccessMockProvider("gemini")
    p3 = DeterministicFallbackProvider()

    router = LLMRouter(providers=[p1, p2, p3])
    diag = router.diagnose_case(context=sample_context, db=db_session, case_id="case_1")

    assert diag.recommended_strategy == "PAYMENT_LINK"

    invocations = db_session.query(LLMInvocation).filter_by(recovery_case_id="case_1").all()
    assert len(invocations) == 1
    assert invocations[0].provider == "openai"
    assert invocations[0].success is True
    assert invocations[0].fallback_triggered is False

def test_router_single_fallback(db_session: Session, sample_context):
    """Verify primary fails -> secondary succeeds and logs both invocations."""
    p1 = AlwaysFailingMockProvider("openai")
    p2 = AlwaysSuccessMockProvider("gemini", strategy="RETRY")
    p3 = DeterministicFallbackProvider()

    router = LLMRouter(providers=[p1, p2, p3])
    diag = router.diagnose_case(context=sample_context, db=db_session, case_id="case_2")

    assert diag.recommended_strategy == "RETRY"

    invocations = db_session.query(LLMInvocation).filter_by(recovery_case_id="case_2").all()
    assert len(invocations) == 2

    # OpenAI attempt (failed)
    assert invocations[0].provider == "openai"
    assert invocations[0].success is False
    assert invocations[0].fallback_triggered is True

    # Gemini attempt (succeeded)
    assert invocations[1].provider == "gemini"
    assert invocations[1].success is True
    assert invocations[1].fallback_triggered is True

def test_router_double_fallback_to_deterministic(db_session: Session, sample_context):
    """Verify primary & secondary fail -> deterministic succeeds."""
    p1 = AlwaysFailingMockProvider("openai")
    p2 = AlwaysFailingMockProvider("gemini")
    p3 = DeterministicFallbackProvider()

    router = LLMRouter(providers=[p1, p2, p3])
    diag = router.diagnose_case(context=sample_context, db=db_session, case_id="case_3")

    assert diag.recommended_strategy == "PAYMENT_LINK"

    invocations = db_session.query(LLMInvocation).filter_by(recovery_case_id="case_3").all()
    assert len(invocations) == 3

    assert invocations[0].provider == "openai" and invocations[0].success is False
    assert invocations[1].provider == "gemini" and invocations[1].success is False
    assert invocations[2].provider == "deterministic" and invocations[2].success is True
    assert invocations[2].fallback_triggered is True

# -----------------------------------------------------------------------------
# 4. Simulation Flags & Prompt Integrity Tests
# -----------------------------------------------------------------------------

def test_openai_simulated_failure_flag():
    settings.SIMULATE_OPENAI_FAILURE = True
    provider = OpenAIProvider(api_key="sk-fake-key")

    with pytest.raises(LLMProviderError) as exc_info:
        provider.diagnose({})
    assert "Simulated OpenAI provider failure" in str(exc_info.value)

    settings.SIMULATE_OPENAI_FAILURE = False

def test_gemini_simulated_failure_flag():
    settings.SIMULATE_GEMINI_FAILURE = True
    provider = GeminiProvider(api_key="fake-key")

    with pytest.raises(LLMProviderError) as exc_info:
        provider.diagnose({})
    assert "Simulated Gemini provider failure" in str(exc_info.value)

    settings.SIMULATE_GEMINI_FAILURE = False

def test_prompt_no_hidden_ground_truth_leakage(sample_context):
    prompt = build_user_prompt(sample_context)
    prompt_lower = prompt.lower()

    forbidden_terms = [
        "simulation_ground_truth",
        "true_recovery_probability",
        "simulated_outcome",
        "future_outcome",
    ]
    for term in forbidden_terms:
        assert term not in prompt_lower, f"Forbidden leakage term '{term}' found in user prompt!"
